title: Documenting the Now
email: info@docnow.io
description: >
  Documenting the Now develops tools and builds community practices that
  support the ethical collection, use, and preservation of social media
  content.
baseurl: "/docnow.github.io"
markdown: kramdown

include:
  - .well-known

ignore:
  - Makefile

keep_files:
  - .dat
  - dat.json
  - videos
