title: Documenting the Now
email: info@docnow.io
description: > 
  Documenting the Now develops tools and builds community practices that  
  support the ethical collection, use, and preservation of social media 
  content.
baseurl: ""
url: "http://www.docnow.io"
markdown: kramdown

keep_files:
  - .dat
  - dat.json
  - videos  
